name: Build and Publish

on:
  push:
    branches:
      - develop 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  publish:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: |
            git config user.name $GITHUB_ACTOR
            git config user.email gh-actions-${GITHUB_ACTOR}@senecacollege.ca
            npm config set //github.senecacollege.ca/_registry/npm/:_authToken=${{secrets.PAT_TOKEN}
      - run: npm publish